const INIT_SESSION = 'INIT_SESSION'
const GET_STAVE_GROUPS = 'GET_STAVE_GROUPS'
const KEY_PRESSED_CONTROL = 'KEY_PRESSED_CONTROL';
const KEY_RELEASED_CONTROL = 'KEY_RELEASED_CONTROL';
export default { INIT_SESSION, GET_STAVE_GROUPS, KEY_PRESSED_CONTROL, KEY_RELEASED_CONTROL };
