const UPLOAD_SHEET = 'UPLOAD_SHEET';
const ORIGINAL_SHEET = 'ORIGINAL_SHEET';
const DETECTED_SHEET = 'DETECTED_SHEET';

const MULTI_CLICK_STAVE_SECTION = 'MULTI_CLICK_STAVE_SECTION';
const MERGE_STAVE_SECTIONS = 'MERGE_STAVE_SECTIONS';
const SPLIT_STAVE_SECTIONS = 'SPLIT_STAVE_SECTIONS';
export default { UPLOAD_SHEET, ORIGINAL_SHEET, DETECTED_SHEET};
