const UPLOAD_SHEET = 'UPLOAD_SHEET';
const ORIGINAL_SHEET = 'ORIGINAL_SHEET';
const UNSTAVED_SHEET = 'UNSTAVED_SHEET';
const DETECTED_SHEET = 'DETECTED_SHEET';

export default { UPLOAD_SHEET, ORIGINAL_SHEET, UNSTAVED_SHEET, DETECTED_SHEET};
