const INIT_SESSION = 'INIT_SESSION'

const ORIGINAL_SHEET = 'ORIGINAL_SHEET';
const UNSTAVED_SHEET = 'UNSTAVED_SHEET';
const DETECTED_SHEET = 'DETECTED_SHEET';

export default {
 INIT_SESSION,
 ORIGINAL_SHEET,
 UNSTAVED_SHEET,
 DETECTED_SHEET,
};
