/**
* Session.js
* Session Action
* Author: Ha Jin Song
* Last Modified: 28-May-2017
*/

const INIT_SESSION = 'INIT_SESSION'

const ORIGINAL_SHEET = 'ORIGINAL_SHEET';
const UNSTAVED_SHEET = 'UNSTAVED_SHEET';
const DETECTED_SHEET = 'DETECTED_SHEET';

const EDIT_UNSTAVED_SHEET = 'EDIT_UNSTAVED_SHEET';

export default {
 INIT_SESSION,
 ORIGINAL_SHEET,
 UNSTAVED_SHEET,
 DETECTED_SHEET,
 EDIT_UNSTAVED_SHEET,
};
