const UPLOAD_SHEET = 'UPLOAD_SHEET';
const ORIGINAL_SHEET = 'ORIGINAL_SHEET';
const DETECTED_SHEET = 'DETECTED_SHEET';

const GET_STAVE_GROUPS = 'GET_STAVE_GROUPS'

const STAVE_CLICKED_CONTROL = 'STAVE_CLICKED_CONTROL';
const STAVE_CLICKED = 'STAVE_CLICKED'
const MERGE_STAVE_SECTIONS = 'MERGE_STAVE_SECTIONS';
const SPLIT_STAVE_SECTIONS = 'SPLIT_STAVE_SECTIONS';

const ADD_NOTE = 'ADD_NOTE';
export default { UPLOAD_SHEET, ORIGINAL_SHEET, DETECTED_SHEET, GET_STAVE_GROUPS, MERGE_STAVE_SECTIONS, STAVE_CLICKED_CONTROL, STAVE_CLICKED, ADD_NOTE };
