/**
* Sheet.js
* Sheet Action
* Author: Ha Jin Song
* Last Modified: 5-June-2017
*/

const GET_STAVE_GROUPS = 'GET_STAVE_GROUPS'

const STAVE_CLICKED_CONTROL = 'STAVE_CLICKED_CONTROL';
const STAVE_CLICKED = 'STAVE_CLICKED'
const MERGE_STAVE_SECTIONS = 'MERGE_STAVE_SECTIONS';
const SPLIT_STAVE_SECTIONS = 'SPLIT_STAVE_SECTIONS';

const ADD_NOTE = 'ADD_NOTE';
const REMOVE_NOTE = 'REMOVE_NOTE';
const EDIT_NOTE = 'EDIT_NOTE';
const NOTE_CLICKED_CONTROL = 'NOTE_CLICKED_CONTROL';

const GROUP_AS_BAR = 'GROUP_AS_BAR';
const GROUP_AS_SLUR = 'GROUP_AS_SLUR';
const ADD_ARTICULATION = 'ADD_ARTICULATION';

const TRANSPOSE = 'TRANSPOSE';
const ANNOTATE = 'ANNOTATE';

const SET_REPEAT_START = 'SET_REPEAT_START';
const SET_REPEAT_END = 'SET_REPEAT_END';

export default {
 GET_STAVE_GROUPS,
 MERGE_STAVE_SECTIONS,
 STAVE_CLICKED_CONTROL,
 STAVE_CLICKED,
 ADD_NOTE,
 REMOVE_NOTE,
 EDIT_NOTE,
 NOTE_CLICKED_CONTROL,
 GROUP_AS_BAR,
 GROUP_AS_SLUR,
 ADD_ARTICULATION,
 TRANSPOSE,
 ANNOTATE,
 SET_REPEAT_START,
 SET_REPEAT_END,

};
