/**
* symbols.js
* symbols Action
* Author: Ha Jin Song
* Last Modified: 28-May-2017
*/

const CROP_NORMAL_NOTE = 'CROP_NORMAL_NOTE';
const CROP_HALF_NOTE = 'CROP_HALF_NOTE';
const CROP_WHOLE_NOTE = 'CROP_WHOLE_NOTE';
const CROP_NORMAL_REST = 'CROP_NORMAL_REST';
const CROP_HALF_REST ='CROP_NORMAL_REST';
const CROP_QUAVER_REST = 'CROP_QUAVER_REST';
const CROP_SEMI_QUAVER_REST = 'CROP_SEMI_QUAVER_REST';
const CROP_DEMI_SEMI_QUAVER_REST = 'CROP_DEMI_SEMI_QUAVER_REST';
const CROP_FLAT = 'CROP_FLAT';
const CROP_SHARP = 'CROP_SHARP';

export default {
 CROP_NORMAL_NOTE,
 CROP_HALF_NOTE,
 CROP_WHOLE_NOTE,
 CROP_NORMAL_REST,
 CROP_HALF_REST,
 CROP_QUAVER_REST,
 CROP_SEMI_QUAVER_REST,
 CROP_DEMI_SEMI_QUAVER_REST,
 CROP_FLAT,
 CROP_SHARP,
};
