const CROP_NORMAL_NOTE = 'CROP_NORMAL_NOTE';
const CROP_HALF_NOTE = 'CROP_HALF_NOTE';
const CROP_WHOLE_NOTE = 'CROP_WHOLE_NOTE';
const CROP_FLAT = 'CROP_FLAT';
const CROP_SHARP = 'CROP_SHARP';

export default { CROP_NORMAL_NOTE, CROP_HALF_NOTE, CROP_WHOLE_NOTE, CROP_FLAT, CROP_SHARP };
